Here you'll find a shell script for building emacs on macos, along with a few
other useful bits.

There is, of course, the great [[https://emacsformacosx.com][Emacs for macos]]. This is probably the most
straightforward way to get emacs for the mac. There is also [[https://brew.sh][homebrew]] and the
various ways of building emacs for that. Three great ones are:

- https://github.com/d12frosted/homebrew-emacs-plus
- https://github.com/daviderestivo/homebrew-emacs-head
- https://github.com/railwaycat/homebrew-emacsmacport

There are also a few great sources for looking at how to build emacs on macos. See
for example:

- https://github.com/jimeh/build-emacs-for-macos
- https://github.com/renard/emacs-build-macosx


So why another build script? Well, in keeping with the way I use emacs, I wanted to be able to build it in the way that I preferred, using all the options that I thought important. Plus I also wanted to understand more about the build process. Since I'm not a programmer, I tried to write a [[https://en.wikipedia.org/wiki/Shell_script][shell script]] that would be as accessible to other non-programmers as possible. It was this latter that I found particularly lacking in my search on the internet for instructions about how to build emacs using any but the most basic of settings. So below you'll find a discussion of the various contents of this repo, what they do (to the best of my very limited knowledge) and why they are there. Hopefully this will be of help to those people who, like myself, want more control over how emacs works but lack much of the programming knowledge that is assumed for building it.

** Emacs & Git
The first thing one needs to do in building emacs is clone the emacs git repository. The first thing one needs is to have git on their system. You can get it from homebrew via =brew git= or from [[https://git-scm.com][their website]]. Then you need to "clone" (i.e. copy) the emacs git repository. You can do this either by cloning from the main repo: =git clone https://git.savannah.gnu.org/git/emacs.git= or from the github mirror: =git clone https://github.com/emacs-mirror/emacs.git=. It doesn't really matter which one you choose in terms of content, just whether you'd rather be connecting to github or not.

** Config Options

[[file:config-options.txt][Config-options.txt]] lists the various options one can use to build emacs.
It is generated by running =./autogen.sh= in the emacs git repo. There are many
to choose from, though slightly less so on macos. 

** Patches

- Lion fullscreen
- No window refocus
- Git version
- System appearance
- Windowing

** Build-emacs.sh

Please note that large portions of the build script are derived from, or
inspired by:

- https://github.com/renard/emacs-build-macosx
- https://github.com/d12frosted/homebrew-emacs-plus
- https://github.com/jimeh/build-emacs-for-macos


